# Generated by Django 6.0.2 on 2026-02-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN-13')),
                ('format', models.CharField(blank=True, max_length=50, null=True)),
                ('book_depot_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_depot_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('stock', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx')],
            },
        ),
    ]
